version: "3.8"

services:
    laravel:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
